# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_travelregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='duration',
            field=models.CharField(default='', max_length=20),
        ),
    ]
