# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_travel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='distance',
            field=models.CharField(default='', max_length=20),
        ),
    ]
