# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 23:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(default='+359', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be enteredin the format: +359XXXXXXXXX', regex='^\\+359?\\d{9}$')])),
            ],
        ),
    ]
